"LOP_CDF_Infantry_Rifleman",
"LOP_CDF_Infantry_Pilot",
"LOP_CDF_Infantry_TL",
"LOP_CDF_Infantry_SL",
"LOP_CDF_Infantry_Crewman",
"LOP_CDF_Infantry_Corpsman",
"LOP_CDF_Infantry_Officer",
"LOP_CDF_Infantry_Marksman",
"LOP_CDF_Infantry_AA",
"LOP_CDF_Infantry_AT",
"LOP_CDF_Infantry_AT_Asst",
"LOP_CDF_Infantry_GL",
"LOP_CDF_Infantry_MG",
"LOP_CDF_Infantry_MG_Asst",
"LOP_CDF_Infantry_Engineer",
 
"LOP_CDF_T72BB",
"LOP_CDF_T72BA",
"LOP_CDF_BMD1",
"LOP_CDF_BMP2D",
"LOP_CDF_BMP2",
"LOP_CDF_BMP1",
"LOP_CDF_BMP1D",
"LOP_CDF_ZSU234",
"LOP_CDF_BTR60",
"LOP_CDF_BTR70",
 
"LOP_CDF_KAMAZ_Covered",
"LOP_CDF_KAMAZ_Transport",
"LOP_CDF_KAMAZ_Repair",
"LOP_CDF_KAMAZ_Fuel",
"LOP_CDF_KAMAZ_Ammo",
"LOP_CDF_KAMAZ_Medical",
"LOP_CDF_BM21",
"LOP_CDF_Ural",
"LOP_CDF_Ural_open",
"LOP_CDF_UAZ",
"LOP_CDF_UAZ_Open",
 
"LOP_CDF_Mi24V_UPK23",
"LOP_CDF_Mi24V_FAB",
"LOP_CDF_Mi24V_AT",
"LOP_CDF_Mi8AMTSh_UPK23",
"LOP_CDF_Mi8AMTSh_FAB",
"LOP_CDF_Mi8MT_Cargo",
"LOP_CDF_Mi8MTV3_FAB",
"LOP_CDF_Mi8MTV3_UPK23",
 
"LOP_CDF_NSV_TriPod",
"LOP_CDF_Static_M2",
"LOP_CDF_Static_M2_MiniTripod",
"LOP_CDF_Static_Mk19_TriPod"
 
 
"LOP_U_CDF_Fatigue_01",
"LOP_V_6B23_CDF",
"LOP_V_6B23_OLV",
"LOP_V_6B23_6Sh92_CDF",
"LOP_V_6B23_6Sh92_OLV",
"LOP_V_6B23_CrewOfficer_CDF",
"LOP_V_6B23_CrewOfficer_OLV",
"LOP_V_6B23_Rifleman_CDF",
"LOP_V_6B23_Rifleman_OLV",
"LOP_V_6B23_Medic_CDF",
"LOP_V_6B23_Medic_OLV",
"LOP_V_6Sh92_CDF",
"LOP_V_6Sh92_OLV",
"LOP_H_Fieldcap_CDF",
"LOP_H_6B27M_ess_CDF"
 
"LOP_AA_Infantry_TL",
"LOP_AA_Infantry_SL",
"LOP_AA_Infantry_Corpsman",
"LOP_AA_Infantry_Rifleman",
"LOP_AA_Infantry_AT",
"LOP_AA_Infantry_AT_Asst",
"LOP_AA_Infantry_MG_Asst",
"LOP_AA_Infantry_MG",
"LOP_AA_Infantry_Engineer",
"LOP_AA_Infantry_Marksman",
"LOP_AA_Infantry_GL",
 
"LOP_AA_Truck",
"LOP_AA_Offroad",
"LOP_AA_Offroad_Police",
"LOP_AA_Offroad_M2",
"LOP_AA_Offroad_M2_Police",
"LOP_AA_M998_D_4DR",
"LOP_AA_M1025_W_M2",
"LOP_AA_M1025_W_Mk19",
"LOP_AA_M1025_D",
 
"LOP_AA_M113_W",
"LOP_AA_BMP2",
"LOP_AA_BMP1",
"LOP_AA_ZSU234",
 
 
"LOP_AA_Static_M2",
"LOP_AA_Static_M2_MiniTripod",
"LOP_AA_Static_Mk19_TriPod",
 
"LOP_AA_Police_TL",
"LOP_AA_Police_SL",
"LOP_AA_Police_Corpsman",
"LOP_AA_Police_Rifleman",
"LOP_AA_Police_MG"
 
"LOP_H_6B27M_ANA",
"LOP_H_6B27M_ess_ANA",
"LOP_H_6B27M_WDL",
"LOP_H_6B27M_ess_WDL",
"LOP_U_AA_Fatigue_01",
"LOP_U_AA_Fatigue_01_slv",
"LOP_U_AA_Fatigue_02",
"LOP_U_AA_Fatigue_02_slv",
"LOP_V_Carrier_OLV",
"LOP_V_Carrier_TAN",
"LOP_V_Carrier_ANA",
"LOP_V_Carrier_WDL",
"LOP_V_Carrier_BLK",
"LOP_V_CarrierLite_OLV",
"LOP_V_CarrierLite_TAN",
"LOP_V_CarrierLite_ANA",
"LOP_V_CarrierLite_WDL",
"LOP_V_CarrierRig_OLV",
"LOP_V_CarrierRig_TAN",
"LOP_V_CarrierRig_ANA",
"LOP_V_CarrierRig_WDL",
"LOP_U_AA_Fatigue_01",
"LOP_U_AA_Fatigue_01_slv",
"LOP_U_AA_Fatigue_02",
"LOP_U_AA_Fatigue_02_slv",
"LOP_U_AA_Fatigue_03",
"LOP_U_AA_Fatigue_03_slv",
 
 
"LOP_AFR_Infantry_TL",
"LOP_AFR_Infantry_SL",
"LOP_AFR_Infantry_Corpsman",
"LOP_AFR_Infantry_AR",
"LOP_AFR_Infantry_AT",
"LOP_AFR_Infantry_Marksman",
"LOP_AFR_Infantry_IED",
"LOP_AFR_Infantry",
"LOP_AFR_Driver",
"LOP_AFR_Infantry_GL",
 
"LOP_AFR_BTR60",
"LOP_AFR_T72BA",
"LOP_AFR_M113_W",
"LOP_AFR_Landrover",
"LOP_AFR_Landrover_M2",
"LOP_AFR_Offroad_M2",
"LOP_AFR_Offroad",
"LOP_AFR_Truck"
 
"LOP_AFR_Civ_Man_01",
"LOP_AFR_Civ_Man_02",
"LOP_AFR_Civ_Man_03",
"LOP_AFR_Civ_Man_04",
"LOP_AFR_Civ_Offroad",
"LOP_AFR_Civ_Hatchback",
"LOP_AFR_Civ_Ural",
"LOP_AFR_Civ_Ural_open",
"LOP_AFR_Civ_UAZ",
"LOP_AFR_Civ_Landrover",
"LOP_AFR_Civ_UAZ_Open"
 
"LOP_AM_Infantry_TL",
"LOP_AM_Infantry_SL",
"LOP_AM_Infantry_Medic",
"LOP_AM_Infantry_AR",
"LOP_AM_Infantry_AT",
"LOP_AM_Infantry_Marksman",
"LOP_AM_Infantry_Engineer",
"LOP_AM_Soldier",
"LOP_AM_Infantry_GL",
 
"LOP_AM_Landrover",
"LOP_AM_Landrover_M2",
"LOP_AM_Offroad",
"LOP_AM_Offroad_M2",
"LOP_AM_Truck",
"LOP_AM_M113_W",
"LOP_AM_BTR60",
"LOP_AM_T72BA",
"LOP_AM_Static_M2",
"LOP_AM_Static_M2_MiniTripod",
"LOP_AM_Static_Mk19_TriPod",
 
"LOP_ChDKZ_Infantry_Bardak",
"LOP_ChDKZ_Infantry_Commander",
"LOP_ChDKZ_Infantry_TL",
"LOP_ChDKZ_Infantry_Corpsman",
"LOP_ChDKZ_Infantry_SL",
"LOP_ChDKZ_Infantry_Rifleman",
"LOP_ChDKZ_Infantry_GL",
"LOP_ChDKZ_Infantry_AT",
"LOP_ChDKZ_Infantry_MG",
"LOP_ChDKZ_Infantry_Marksman",
"LOP_ChDKZ_Infantry_Engineer",
"LOP_ChDKZ_Infantry_Crewman",
"LOP_ChDKZ_Infantry_Pilot",
 
 
 
"LOP_ChDKZ_T72BB",
"LOP_ChDKZ_T72BA",
"LOP_ChDKZ_BMP2D",
"LOP_ChDKZ_BMP2",
"LOP_ChDKZ_BMP1",
"LOP_ChDKZ_BMP1D",
"LOP_ChDKZ_ZSU234",
"LOP_ChDKZ_BTR60",
"LOP_ChDKZ_BTR70",
 
"LOP_ChDKZ_BM21",
"LOP_ChDKZ_Ural",
"LOP_ChDKZ_Ural_open",
"LOP_ChDKZ_UAZ",
"LOP_ChDKZ_UAZ_Open",
 
"LOP_ChDKZ_NSV_TriPod",
 
"LOP_ChDKZ_Mi8MT_Cargo",
"LOP_ChDKZ_Mi8MTV3_FAB",
"LOP_ChDKZ_Mi8MTV3_UPK23"
 
"LOP_U_ChDKZ_Fatigue_Commander",
"LOP_U_ChDKZ_Fatigue_01",
"LOP_U_ChDKZ_Fatigue_02",
"LOP_U_ChDKZ_Fatigue_03",
"LOP_U_ChDKZ_Fatigue_04",
"LOP_U_ChDKZ_Fatigue_Bardak"
 
"LOP_IA_Infantry_TL",
"LOP_IA_Infantry_SL",
"LOP_IA_Infantry_Corpsman",
"LOP_IA_Infantry_Rifleman",
"LOP_IA_Infantry_AT",
"LOP_IA_Infantry_AT_Asst",
"LOP_IA_Infantry_MG_Asst",
"LOP_IA_Infantry_MG",
"LOP_IA_Infantry_Engineer",
"LOP_IA_Infantry_Marksman",
"LOP_IA_Infantry_GL",
 
"LOP_IA_Truck",
"LOP_IA_Offroad",
"LOP_IA_Offroad_M2",
"LOP_IA_M998_D_4DR",
"LOP_IA_M1025_W_M2",
"LOP_IA_M1025_W_Mk19",
"LOP_IA_M1025_D",
 
"LOP_IA_M113_W",
"LOP_IA_BMP2",
"LOP_IA_BMP1",
"LOP_IA_ZSU234",
 
 
"LOP_IA_Static_M2",
"LOP_IA_Static_M2_MiniTripod",
"LOP_IA_Static_Mk19_TriPod"
 
"LOP_H_6B27M_TRI",
"LOP_H_6B27M_ess_TRI",
"LOP_U_IA_Fatigue_01",
"LOP_U_IA_Fatigue_01_slv"
 
"LOP_ISTS_Infantry_TL",
"LOP_ISTS_Infantry_SL",
"LOP_ISTS_Infantry_Medic",
"LOP_ISTS_Infantry_AR",
"LOP_ISTS_Infantry_AT",
"LOP_ISTS_Infantry_Marksman",
"LOP_ISTS_Infantry_Engineer",
"LOP_ISTS_Soldier",
"LOP_ISTS_Infantry_GL",
 
"LOP_ISTS_Landrover",
"LOP_ISTS_Landrover_M2",
"LOP_ISTS_Offroad",
"LOP_ISTS_Offroad_M2",
"LOP_ISTS_Truck",
"LOP_ISTS_M113_W",
"LOP_ISTS_BTR60",
"LOP_ISTS_T72BA",
"LOP_ISTS_Static_M2",
"LOP_ISTS_Static_M2_MiniTripod",
"LOP_ISTS_Static_Mk19_TriPod",
 
"LOP_RACS_Infantry_TL",
"LOP_RACS_Infantry_SL",
"LOP_RACS_Infantry_Corpsman",
"LOP_RACS_Infantry_Rifleman",
"LOP_RACS_Infantry_AT",
"LOP_RACS_Infantry_AT_Asst",
"LOP_RACS_Infantry_MG_Asst",
"LOP_RACS_Infantry_MG",
"LOP_RACS_Infantry_Engineer",
"LOP_RACS_Infantry_Marksman",
"LOP_RACS_Infantry_GL",
"LOP_RACS_Infantry_Crewman",
"LOP_RACS_Infantry_Pilot",
 
"LOP_RACS_Truck",
"LOP_RACS_Offroad",
"LOP_RACS_Offroad_M2",
"LOP_RACS_Landrover",
"LOP_RACS_Landrover_M2",
 
"LOP_RACS_M113_W",
"LOP_RACS_T72BA",
 
 
"LOP_RACS_Static_M2",
"LOP_RACS_Static_M2_MiniTripod",
"LOP_RACS_Static_Mk19_TriPod"
 
"LOP_H_6B27M_RACS",
"LOP_H_6B27M_ess_RACS",
"LOP_H_Booniehat_RACS"
 
 
"LOP_SLA_Infantry_Rifleman",
"LOP_SLA_Infantry_Pilot",
"LOP_SLA_Infantry_TL",
"LOP_SLA_Infantry_SL",
"LOP_SLA_Infantry_Crewman",
"LOP_SLA_Infantry_Corpsman",
"LOP_SLA_Infantry_Officer",
"LOP_SLA_Infantry_Marksman",
"LOP_SLA_Infantry_AA",
"LOP_SLA_Infantry_AT",
"LOP_SLA_Infantry_AT_Asst",
"LOP_SLA_Infantry_GL",
"LOP_SLA_Infantry_MG",
"LOP_SLA_Infantry_MG_Asst",
"LOP_SLA_Infantry_Engineer",
 
"LOP_SLA_T72BB",
"LOP_SLA_T72BA",
"LOP_SLA_BMP2D",
"LOP_SLA_BMP2",
"LOP_SLA_BMP1",
"LOP_SLA_BMP1D",
"LOP_SLA_ZSU234",
"LOP_SLA_BTR60",
"LOP_SLA_BTR70",
 
"LOP_SLA_BM21",
"LOP_SLA_Ural",
"LOP_SLA_Ural_open",
"LOP_SLA_UAZ",
"LOP_SLA_UAZ_Open",
 
"LOP_SLA_NSV_TriPod",
 
"LOP_U_SLA_Fatigue_01",
"LOP_H_SSh68Helmet_OLV",
"LOP_H_SSh68Helmet_BLK",
"LOP_H_SLA_Beret"
 
"LOP_Tak_Civ_Man_01",
"LOP_Tak_Civ_Man_02",
"LOP_Tak_Civ_Man_03",
"LOP_Tak_Civ_Man_04",
"LOP_TAK_Civ_Offroad",
"LOP_TAK_Civ_Hatchback",
"LOP_TAK_Civ_Landrover",
"LOP_TAK_Civ_Ural",
"LOP_TAK_Civ_Ural_open",
"LOP_TAK_Civ_UAZ",
"LOP_TAK_Civ_UAZ_Open"
 
"LOP_US_Infantry_Rifleman",
"LOP_US_Infantry_Pilot",
"LOP_US_Infantry_TL",
"LOP_US_Infantry_SL",
"LOP_US_Infantry_Crewman",
"LOP_US_Infantry_Corpsman",
"LOP_US_Infantry_Officer",
"LOP_US_Infantry_Marksman",
"LOP_US_Infantry_AA",
"LOP_US_Infantry_AT",
"LOP_US_Infantry_AT_Asst",
"LOP_US_Infantry_GL",
"LOP_US_Infantry_MG",
"LOP_US_Infantry_MG_Asst",
"LOP_US_Infantry_Engineer",
 
"LOP_US_T72BB",
"LOP_US_T72BA",
"LOP_US_BMP2D",
"LOP_US_BMP2",
"LOP_US_BMP1",
"LOP_US_BMP1D",
"LOP_US_ZSU234",
"LOP_US_BTR60",
"LOP_US_BTR70",
 
"LOP_US_BM21",
"LOP_US_Ural",
"LOP_US_Ural_open",
"LOP_US_UAZ",
"LOP_US_UAZ_Open",
 
"LOP_US_NSV_TriPod",